# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/christopolise/FALL_2020/ECEN_427/labs/427-labs-christopolise/hw/vip_simulation/pit_ip_vip_simulation/pit_ip_vip_simulation.srcs/sources_1/bd/design_1/ip/design_1_axi_vip_0_0/design_1_axi_vip_0_0.xci
# IP: The module: 'design_1_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/christopolise/FALL_2020/ECEN_427/labs/427-labs-christopolise/hw/vip_simulation/pit_ip_vip_simulation/pit_ip_vip_simulation.srcs/sources_1/bd/design_1/ip/design_1_axi_vip_0_0/design_1_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/christopolise/FALL_2020/ECEN_427/labs/427-labs-christopolise/hw/vip_simulation/pit_ip_vip_simulation/pit_ip_vip_simulation.srcs/sources_1/bd/design_1/ip/design_1_axi_vip_0_0/design_1_axi_vip_0_0.xci
# IP: The module: 'design_1_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/christopolise/FALL_2020/ECEN_427/labs/427-labs-christopolise/hw/vip_simulation/pit_ip_vip_simulation/pit_ip_vip_simulation.srcs/sources_1/bd/design_1/ip/design_1_axi_vip_0_0/design_1_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
